"on":
  workflow_dispatch:
    inputs:
      deployment_id:
        description: Deployment ID
        required: true
        type: number
name: Porter Preview Environment
jobs:
  porter-delete-preview:
    runs-on: ubuntu-latest
    steps:
    - name: Delete Porter preview env
      timeout-minutes: 30
      uses: porter-dev/porter-delete-preview-action@v0.2.0
      with:
        cluster: "1"
        deployment_id: ${{ github.event.inputs.deployment_id }}
        host: https://a58a-181-9-167-80.ngrok.io
        project: "1"
        token: ${{ secrets.PORTER_TOKEN_1 }}
